# Generated by Django 5.0 on 2023-12-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ник'),
        ),
    ]
