# Generated by Django 4.2.4 on 2024-01-01 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=35,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите действительный номер телефона.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="номер телефона",
            ),
        ),
    ]
