# Generated by Django 4.2.4 on 2024-01-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="дата оплаты"),
                ),
                (
                    "amount",
                    models.FloatField(
                        blank=True, null=True, verbose_name="сумма оплаты"
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="подтверждение оплаты"
                    ),
                ),
                (
                    "stripe_session_id",
                    models.TextField(
                        blank=True, null=True, verbose_name="id платежной сессии"
                    ),
                ),
            ],
            options={
                "verbose_name": "платеж",
                "verbose_name_plural": "платежи",
                "ordering": ("date",),
            },
        ),
    ]
