# Generated by Django 4.2.4 on 2023-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.TextField(blank=True, null=True, verbose_name='id платежной сессии'),
        ),
    ]
