# Generated by Django 4.2.4 on 2023-12-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_stripe_session_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
